import Foundation

// MARK: - User Content

/// An enum representing various types of user content information.
enum UserContentCategory: String, Codable, CollectedCategory {
    /// Including subject line, sender, recipients, and contents of the email or message.
    case emailsOrTextMessages = "NSPrivacyCollectedDataTypeEmailsOrTextMessages"

    /// The user’s photos or videos.
    case photosOrVideos = "NSPrivacyCollectedDataTypePhotosorVideos"

    /// The user’s voice or sound recordings.
    case audioData = "NSPrivacyCollectedDataTypeAudioData"

    /// Such as saved games, multiplayer matching or gameplay logic, or user-generated content in-game.
    case gameplayContent = "NSPrivacyCollectedDataTypeGameplayContent"

    /// Data generated by the user during a customer support request.
    case customerSupport = "NSPrivacyCollectedDataTypeCustomerSupport"

    /// Any other user-generated content.
    case otherUserContent = "NSPrivacyCollectedDataTypeOtherUserContent"

    var id: String { rawValue }

    var title: String {
        switch self {
        case .emailsOrTextMessages:
            "Emails or text messages"
        case .photosOrVideos:
            "Photos or videos"
        case .audioData:
            "Audio data"
        case .gameplayContent:
            "Gameplay content"
        case .customerSupport:
            "Customer support"
        case .otherUserContent:
            "Other user content"
        }
    }

    var description: String {
        switch self {
        case .emailsOrTextMessages:
            return "Including subject line, sender, recipients, and contents of the email or message."
        case .photosOrVideos:
            return "The user’s photos or videos."
        case .audioData:
            return "The user’s voice or sound recordings."
        case .gameplayContent:
            return "Such as saved games, multiplayer matching or gameplay logic, or user-generated content in-game."
        case .customerSupport:
            return "Data generated by the user during a customer support request."
        case .otherUserContent:
            return "Any other user-generated content."
        }
    }
}
